version: '3.7'
services:
  mongodb:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  unpub:
    container_name: unpub
    image: trevorwang/docker-unpub:latest 
    restart: always
    depends_on:
        - mongodb
    environment:
      DB_URL: mongodb://mongodb:27017/pub
      WAIT_HOSTS: mongodb:27017
    volumes:
      - unpub_app:/app
    ports:
      - 4000:4000

volumes:
  mongodb_data_container:
  unpub_app: